<?php
// Encrypted By BricksApp PHP  
// Author : Nizar Rahmat 
$encoded = "Pz48ZnBldmNnIGdsY3I9Imdya2cvd25pbmZwZXZjZyI+ICANCglzaGFwZ3ZiYSBhbmlfb2hnZ2JhXzw/Y3VjIHJwdWIgJHNoYXBndmJhID8+KCl7DQoJCSQoJyNjbmFyeV9wYmFncmFnXzw/Y3VjIHJwdWIgJHpyZ3VicXZxID8+JykudXZxcigpOw0KCQkkKCcjY25hcnlfcGJhZ3JhZ19zYmV6Xzw/Y3VjIHJwdWIgJHpyZ3VicXZxID8+JykuZnViaigpOw0KCQkNCgkJJCgnLnNiZXpfZ3ZneXJfPD9jdWMgcnB1YiAkenJndWJxdnEgPz4nKS51Z3p5KCdOcXEgPD9jdWMgcnB1YiAkY250cl9ndmd5ciA/PicpOw0KCQkNCgkJJCgnI3NiZXpfPD9jdWMgcnB1YiAkenJndWJxdnEgPz5fZWJ5cl92cScpLmlueSgnJyk7DQoJCSQoJyNzYmV6Xzw/Y3VjIHJwdWIgJHpyZ3VicXZxID8+X2VieXInKS5pbnkoJycpOw0KCQkNCgkJJCgnLmZycGhldmdsX2VieXJfZ2J4cmFfdnEnKS5jZWJjKCdwdXJweHJxJywgc255ZnIpOw0KCX0NCjwvZnBldmNnPg==";
eval(simple_decrypt($encoded, __FILE__));
?>