<?php
// Encrypted By BricksApp PHP  
// Author : Nizar Rahmat 
$encoded = "Pz48P2N1YyBweW5mZiBadmF2c2x1Z3p5IHsgc2hhcGd2YmEgYmhnY2hnKCkgeyAkUFYgPSYgdHJnX3ZhZmduYXByKCk7ICRvaHNzcmUgPSAkUFYtPmJoZ2NoZy0+dHJnX2JoZ2NoZygpOyAkZnJuZXB1ID0gbmVlbmwoICcvXD5bXlxGIF0rL2YnLCAnL1teXEYgXStcPC9mJywgJy8oXGYpKy9mJyApOyAkZXJjeW5wciA9IG5lZW5sKCAnPicsICc8JywgJ1xcMScgKTsgJG9oc3NyZSA9IGNlcnRfZXJjeW5wcigkZnJuZXB1LCAkZXJjeW5wciwgJG9oc3NyZSk7ICRQVi0+YmhnY2hnLT5mcmdfYmhnY2hnKCRvaHNzcmUpOyAkUFYtPmJoZ2NoZy0+X3F2ZmN5bmwoKTsgfSB9ID8+";
eval(simple_decrypt($encoded, __FILE__));
?>