<?php
// Encrypted By BricksApp PHP  
// Author : Nizar Rahmat 
$encoded = "Pz48ZnBldmNnIGdsY3I9Imdya2cvd25pbmZwZXZjZyI+ICANCglzaGFwZ3ZiYSBhbmlfb2hnZ2JhXzw/Y3VjIHJwdWIgJHNoYXBndmJhID8+KCl7DQoJCSQoJyNjbmFyeV9wYmFncmFnXzw/Y3VjIHJwdWIgJHpyZ3VicXZxID8+JykudXZxcigpOw0KCQkkKCcjY25hcnlfcGJhZ3JhZ19zYmV6Xzw/Y3VjIHJwdWIgJHpyZ3VicXZxID8+JykuZnViaigpOw0KCQkNCgkJJCgnLnNiZXpfZ3ZneXJfPD9jdWMgcnB1YiAkenJndWJxdnEgPz4nKS51Z3p5KCdBcmogPD9jdWMgcnB1YiAkY250cl9ndmd5ciA/PicpOw0KCQkkKCcjc2Jlel88P2N1YyBycHViICR6cmd1YnF2cSA/Pl91Zl9wYnFyJykuY2ViYygnZXJucWJheWwnLCBzbnlmcik7DQoJCSQoJyNzYmV6Xzw/Y3VjIHJwdWIgJHpyZ3VicXZxID8+X3VmX3ZxJykuaW55KCcnKTsNCgkJJCgnI3NiZXpfPD9jdWMgcnB1YiAkenJndWJxdnEgPz5fdWZfcGJxcicpLmlueSgnJyk7DQoJCSQoJyNzYmV6Xzw/Y3VjIHJwdWIgJHpyZ3VicXZxID8+X3VmX2FuenInKS5pbnkoJycpOw0KCQkNCgkJZnJnR3Z6cmJoZyhzaGFwZ3ZiYSgpeyANCgkJCSQoJy5nbm9fZnBlYnl5b25lJykudHJnQXZwckZwZWJ5eSgpLmVyZnZtcigpOyANCgkJfSwgMTAwKTsJCQ0KCX0NCjwvZnBldmNnPg==";
eval(simple_decrypt($encoded, __FILE__));
?>