<?php
// Encrypted By BricksApp PHP  
// Author : Nizar Rahmat 
$encoded = "Pz48ZnBldmNnIGdsY3I9Imdya2cvd25pbmZwZXZjZyI+ICANCglzaGFwZ3ZiYSBhbmlfb2hnZ2JhXzw/Y3VjIHJwdWIgJHNoYXBndmJhID8+KCl7DQoJCSQoJyNjbmFyeV9wYmFncmFnXzw/Y3VjIHJwdWIgJHpyZ3VicXZxID8+JykudXZxcigpOw0KCQkkKCcjY25hcnlfcGJhZ3JhZ19zYmV6Xzw/Y3VjIHJwdWIgJHpyZ3VicXZxID8+JykuZnViaigpOw0KCQkNCgkJJCgnLnNiZXpfZ3ZneXJfPD9jdWMgcnB1YiAkenJndWJxdnEgPz4nKS51Z3p5KCdHbmsgR2xjcmYnKTsNCgkJDQoJCSQoJyNzYmV6Xzw/Y3VjIHJwdWIgJHpyZ3VicXZxID8+X2dua19nbGNyX3ZxJykuaW55KCcnKTsNCgkJJCgnI3NiZXpfPD9jdWMgcnB1YiAkenJndWJxdnEgPz5fZ25rX2dsY3InKS5pbnkoJycpOw0KCQkkKCcjc2Jlel88P2N1YyBycHViICR6cmd1YnF2cSA/Pl9nbmtfZW5ncicpLmlueSgnJyk7DQoJCQ0KCX0NCjwvZnBldmNnPg==";
eval(simple_decrypt($encoded, __FILE__));
?>