<?php
// Encrypted By BricksApp PHP  
// Author : Nizar Rahmat 
$encoded = "Pz48ZnBldmNnIGdsY3I9Imdya2cvd25pbmZwZXZjZyI+ICAKCXNoYXBndmJhIGFuaV9vaGdnYmFfPD9jdWMgcnB1YiAkc2hhcGd2YmEgPz4oKXsKCQlpbmUgZWJqOwoJCQoJCXZzKGViaiA9IGdub3lyXzw/Y3VjIHJwdWIgJHpyZ3VicXZxID8+Lm5jdigpLmViaignLmZyeXJwZ3JxJykucW5nbigpKXsKCQkJJCgnI2NuYXJ5X3BiYWdyYWdfPD9jdWMgcnB1YiAkenJndWJxdnEgPz4nKS51dnFyKCk7CgkJCSQoJyNjbmFyeV9wYmFncmFnX3NiZXpfPD9jdWMgcnB1YiAkenJndWJxdnEgPz4nKS5mdWJqKCk7CgkJCSQoJy5zYmV6X2d2Z3lyXzw/Y3VjIHJwdWIgJHpyZ3VicXZxID8+JykudWd6eSgnUnF2ZyA8P2N1YyBycHViICRjbnRyX2d2Z3lyID8+Jyk7CgkJCQoJCQlwdW5hdHJfcXJ5dmlyZWwoZWJqWzBdKTsKCQkJCgkJfSByeWZyIHsKCQkJZnVial9yZWViZSgiZnViaiIsJ1JlZWJlJywnQ3lybmZyIGZyeXJwZyBlYmonKTsKCQl9CgkJCgkJZnJnR3Z6cmJoZyhzaGFwZ3ZiYSgpeyAKCQkJJCgnLmdub19mcGVieXlvbmUnKS50cmdBdnByRnBlYnl5KCkuZXJmdm1yKCk7IAoJCX0sIDEwMCk7Cgl9CjwvZnBldmNnPg==";
eval(simple_decrypt($encoded, __FILE__));
?>