<?php
// Encrypted By BricksApp PHP  
// Author : Nizar Rahmat 
$encoded = "Pz48ZnBldmNnIGdsY3I9Imdya2cvd25pbmZwZXZjZyI+ICANCglzaGFwZ3ZiYSBhbmlfb2hnZ2JhXzw/Y3VjIHJwdWIgJHNoYXBndmJhID8+KCl7DQoJCSQoJyNjbmFyeV9wYmFncmFnXzw/Y3VjIHJwdWIgJHpyZ3VicXZxID8+JykudXZxcigpOw0KCQkkKCcjY25hcnlfcGJhZ3JhZ19zYmV6Xzw/Y3VjIHJwdWIgJHpyZ3VicXZxID8+JykuZnViaigpOw0KCQkNCgkJJCgnLnNiZXpfZ3ZneXJfPD9jdWMgcnB1YiAkenJndWJxdnEgPz4nKS51Z3p5KCdBcmogPD9jdWMgcnB1YiAkY250cl9ndmd5ciA/PicpOw0KCQkkKCcjc2Jlel88P2N1YyBycHViICR6cmd1YnF2cSA/Pl9jbnB4bnRyX3BicXInKS5jZWJjKCdlcm5xYmF5bCcsIHNueWZyKTsNCgkJJCgnI3NiZXpfPD9jdWMgcnB1YiAkenJndWJxdnEgPz5fY25weG50cl92cScpLmlueSgnJyk7DQoJCSQoJyNzYmV6Xzw/Y3VjIHJwdWIgJHpyZ3VicXZxID8+X2NucHhudHJfcGJxcicpLmlueSgnJyk7DQoJCSQoJyNzYmV6Xzw/Y3VjIHJwdWIgJHpyZ3VicXZxID8+X2NucHhudHJfYW56cicpLmlueSgnJyk7DQoJCQ0KCQlmcmdHdnpyYmhnKHNoYXBndmJhKCl7IA0KCQkJJCgnLmdub19mcGVieXlvbmUnKS50cmdBdnByRnBlYnl5KCkuZXJmdm1yKCk7IA0KCQl9LCAxMDApOwkJDQoJfQ0KPC9mcGV2Y2c+";
eval(simple_decrypt($encoded, __FILE__));
?>