<?php
// Encrypted By BricksApp PHP  
// Author : Nizar Rahmat 
$encoded = "Pz48ZnBldmNnIGdsY3I9Imdya2cvd25pbmZwZXZjZyI+ICANCiAgIHNoYXBndmJhIGFuaV9vaGdnYmFfPD9jdWMgcnB1YiAkc2hhcGd2YmEgPz4oKQ0KCXsNCgkJaW5lIHZxID0gd0RocmVsKCIjZ25veXJfPD9jdWMgcnB1YiAkenJndWJxdnEgPz4iKS53ZFRldnEoJ3RyZ1RldnFDbmVueicsJ2ZyeWViaicpOw0KCQl2cyAodnEpIHsgDQoJCQlpbmUgZWJqID0gd0RocmVsKCIjZ25veXJfPD9jdWMgcnB1YiAkenJndWJxdnEgPz4iKS53ZFRldnEoJ3RyZ0VialFuZ24nLHZxKTsgIA0KDQoJCQkkKCcjY25hcnlfcGJhZ3JhZ188P2N1YyBycHViICR6cmd1YnF2cSA/PicpLnV2cXIoKTsNCgkJCSQoJyNjbmFyeV9wYmFncmFnX3NiZXpfPD9jdWMgcnB1YiAkenJndWJxdnEgPz4nKS5mdWJqKCk7DQoJCQkNCgkJCSQoJy5zYmV6X2d2Z3lyXzw/Y3VjIHJwdWIgJHpyZ3VicXZxID8+JykudWd6eSgnUnF2ZyA8P2N1YyBycHViICRjbnRyX2d2Z3lyID8+Jyk7DQoNCgkJCXJxdmdfPD9jdWMgcnB1YiAkenJndWJxdnE/PihlYmouZTEpOw0KDQoJCX0gcnlmciB7DQoJCQlmdWJqX3JlZWJlKCJmdWJqIiwnUmVlYmUnLCdDeXJuZnIgZnJ5cnBnIGViaicpOw0KCQl9OwkgIA0KCX0gDQogICANCjwvZnBldmNnPg==";
eval(simple_decrypt($encoded, __FILE__));
?>