<?php
// Encrypted By BricksApp PHP  
// Author : Nizar Rahmat 
$encoded = "Pz48ZnBldmNnIGdsY3I9Imdya2cvd25pbmZwZXZjZyI+ICANCglzaGFwZ3ZiYSBhbmlfb2hnZ2JhXzw/Y3VjIHJwdWIgJHNoYXBndmJhID8+KCl7DQoJCSQoJyNjbmFyeV9wYmFncmFnXzw/Y3VjIHJwdWIgJHpyZ3VicXZxID8+JykudXZxcigpOw0KCQkkKCcjY25hcnlfcGJhZ3JhZ19zYmV6Xzw/Y3VjIHJwdWIgJHpyZ3VicXZxID8+JykuZnViaigpOw0KCQkNCgkJJCgnLnNiZXpfZ3ZneXJfPD9jdWMgcnB1YiAkenJndWJxdnEgPz4nKS51Z3p5KCdBcmogVmdyeiBRcmdudnknKTsNCgkJJCgnI3NiZXpfPD9jdWMgcnB1YiAkenJndWJxdnEgPz5fdmdyel9wYnFyJykuY2ViYygnZXJucWJheWwnLCBzbnlmcik7CQ0KCQkkKCcjc2Jlel88P2N1YyBycHViICR6cmd1YnF2cSA/Pl92Z3J6X3ZxJykuaW55KCcnKTsNCgkJJCgnI3NiZXpfPD9jdWMgcnB1YiAkenJndWJxdnEgPz5fdmdyel9wYnFyJykuaW55KCcnKTsNCgkJJCgnI3NiZXpfPD9jdWMgcnB1YiAkenJndWJxdnEgPz5fdmdyel9hbnpyJykuaW55KCcnKTsNCgkJDQoJCWZyZ0d2enJiaGcoc2hhcGd2YmEoKXsgDQoJCQkkKCcuZ25vX2ZwZWJ5eW9uZScpLnRyZ0F2cHJGcGVieXkoKS5lcmZ2bXIoKTsgDQoJCX0sIDEwMCk7CQkNCgl9DQo8L2ZwZXZjZz4=";
eval(simple_decrypt($encoded, __FILE__));
?>