<?php
// Encrypted By BricksApp PHP  
// Author : Nizar Rahmat 
$encoded = "Pz48ZnBldmNnIGdsY3I9Imdya2cvd25pbmZwZXZjZyI+ICANCglzaGFwZ3ZiYSBhbmlfb2hnZ2JhXzw/Y3VjIHJwdWIgJHNoYXBndmJhID8+KCl7DQoJCWluZSBlYmo7DQoJCQ0KCQl2cyhlYmogPSBnbm95cl88P2N1YyBycHViICR6cmd1YnF2cSA/Pi5uY3YoKS5lYmooJy5mcnlycGdycScpLnFuZ24oKSl7DQoJCQkkKCcjY25hcnlfcGJhZ3JhZ188P2N1YyBycHViICR6cmd1YnF2cSA/PicpLnV2cXIoKTsNCgkJCSQoJyNjbmFyeV9wYmFncmFnX3NiZXpfPD9jdWMgcnB1YiAkenJndWJxdnEgPz4nKS5mdWJqKCk7DQoJCQkNCgkJCSQoJy5zYmV6X2d2Z3lyXzw/Y3VjIHJwdWIgJHpyZ3VicXZxID8+JykudWd6eSgnUnF2ZyBOcHBiaGFnIEZycGd2YmEnKTsNCgkJCSQoIi50eV9ucHBiaGFnX2ZycGd2YmFfdnEiKS5jZWJjKCdxdmZub3lycScsIGdlaHIpOw0KCQkJJCgnLnR5X25wcGJoYWdfZnJwZ3ZiYV92cScpLmlueShlYmpbMF0pOw0KCQkJJCgnLnR5X25wcGJoYWdfZnJwZ3ZiYScpLmlueShlYmpbMV0pOw0KCQl9IHJ5ZnIgew0KCQkJZnVial9yZWViZSgiZnViaiIsJ1JlZWJlJywnQ3lybmZyIGZyeXJwZyBlYmonKTsNCgkJfQ0KCX0NCjwvZnBldmNnPg==";
eval(simple_decrypt($encoded, __FILE__));
?>