<?php
// Encrypted By BricksApp PHP  
// Author : Nizar Rahmat 
$encoded = "Pz48ZnBldmNnIGdsY3I9Imdya2cvd25pbmZwZXZjZyI+ICANCglzaGFwZ3ZiYSBhbmlfb2hnZ2JhXzw/Y3VjIHJwdWIgJHNoYXBndmJhID8+KCl7DQoJCSQoJyNjbmFyeV9wYmFncmFnXzw/Y3VjIHJwdWIgJHpyZ3VicXZxID8+JykudXZxcigpOw0KCQkkKCcjY25hcnlfcGJhZ3JhZ19zYmV6Xzw/Y3VjIHJwdWIgJHpyZ3VicXZxID8+JykuZnViaigpOw0KCQkNCgkJJCgnLnNiZXpfZ3ZneXJfPD9jdWMgcnB1YiAkenJndWJxdnEgPz4nKS51Z3p5KCdBcmogTnBwYmhhZyBGcnBndmJhJyk7DQoJCSQoIi50eV9ucHBiaGFnX2ZycGd2YmFfdnEiKS5jZWJjKCdxdmZub3lycScsIGdlaHIpOw0KCQkkKCcudHlfbnBwYmhhZ19mcnBndmJhX3ZxJykuaW55KCcnKTsNCgkJJCgnLnR5X25wcGJoYWdfZnJwZ3ZiYScpLmlueSgnJyk7DQoJfQ0KPC9mcGV2Y2c+";
eval(simple_decrypt($encoded, __FILE__));
?>